export function AirPortCode() {
  return [
    { code: "AAA", id: "1" },
    { code: "AAB", id: "2" },
    { code: "AAC", id: "3" },
    { code: "ABA", id: "4" },
    { code: "ABB", id: "5" },
    { code: "ABC", id: "6" },
    { code: "ACA", id: "7" },
    { code: "ACB", id: "8" },
    { code: "ACC", id: "9" },
    { code: "BAA", id: "10" },
    { code: "BAB", id: "11" },
    { code: "BAC", id: "12" },
    { code: "BBA", id: "13" },
    { code: "BBB", id: "14" },
    { code: "BBC", id: "15" },
    { code: "BCA", id: "16" },
    { code: "BCB", id: "17" },
    { code: "BCC", id: "18" },
    { code: "CAA", id: "19" },
    { code: "CAB", id: "20" },
    { code: "CAC", id: "21" },
    { code: "CBA", id: "22" },
    { code: "CBB", id: "23" },
    { code: "CBC", id: "24" },
    { code: "CCA", id: "25" },
    { code: "CCB", id: "26" },
    { code: "CCC", id: "27" },
    { code: "XXX", id: "28" },
    { code: "XXY", id: "29" },
    { code: "XXZ", id: "30" },
    { code: "XYX", id: "31" },
    { code: "XYY", id: "32" },
    { code: "XYZ", id: "33" },
    { code: "XZX", id: "34" },
    { code: "XZY", id: "35" },
    { code: "XZZ", id: "36" },
    { code: "YXX", id: "37" },
    { code: "YXY", id: "38" },
    { code: "YXZ", id: "39" },
    { code: "YYX", id: "40" },
    { code: "YYY", id: "41" },
    { code: "YYZ", id: "42" },
    { code: "YZX", id: "43" },
    { code: "YZY", id: "44" },
    { code: "YZZ", id: "45" },
    { code: "ZXX", id: "46" },
    { code: "ZXY", id: "47" },
    { code: "ZXZ", id: "48" },
    { code: "ZYX", id: "49" },
    { code: "ZYY", id: "50" },
    { code: "ZYZ", id: "51" },
    { code: "ZZX", id: "52" },
    { code: "ZZY", id: "53" },
    { code: "ZZZ", id: "54" },
  ];
}

export function renderAirPortCode(state, val) {
  return state.title.toLowerCase().indexOf(val.toLowerCase()) !== -1;
}
